const THEME_PREFERENCE_KEY = 'membrane.theme.preference'
const ACCENT_PREFERENCE_KEY = 'membrane.theme.accent'

export type ThemePreference = 'system' | 'light' | 'dark'
export type AccentColor = 'red' | 'rose' | 'orange' | 'amber' | 'green' | 'teal' | 'blue' | 'indigo' | 'purple'

type ThemeController = {
  change: (theme: string) => void
  name: Readonly<{ value: string }>
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  themes: Readonly<{ value: Record<string, { colors: Record<string, any> }> }>
}

type AccentPalette = {
  light: Record<string, string>
  dark: Record<string, string>
}

export const ACCENT_DISPLAY: Record<AccentColor, { label: string; lightColor: string; darkColor: string }> = {
  red:    { label: 'Красный',    lightColor: '#B3261E', darkColor: '#FFB4AB' },
  rose:   { label: 'Розовый',   lightColor: '#9E163B', darkColor: '#FFB1C2' },
  orange: { label: 'Оранжевый', lightColor: '#9A4200', darkColor: '#FFB590' },
  amber:  { label: 'Золотой',   lightColor: '#6D5E00', darkColor: '#DCC84C' },
  green:  { label: 'Зелёный',   lightColor: '#006E1C', darkColor: '#7BDB7C' },
  teal:   { label: 'Бирюзовый', lightColor: '#006876', darkColor: '#53D5E7' },
  blue:   { label: 'Синий',     lightColor: '#1565C0', darkColor: '#ADC6FF' },
  indigo: { label: 'Индиго',    lightColor: '#4355B9', darkColor: '#BEC2FF' },
  purple: { label: 'Фиолетовый',lightColor: '#65558F', darkColor: '#D0BCFF' },
}

const ACCENT_PALETTES: Record<AccentColor, AccentPalette> = {
  red: {
    light: {
      primary: '#B3261E',
      'primary-container': '#F9DEDC',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#410E0B',
      secondary: '#775652',
      'secondary-container': '#FFDAD6',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#2C1512',
      tertiary: '#715C2E',
      'tertiary-container': '#FDDEA2',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#261A00',
      'inverse-primary': '#FFB4AB',
      'selection-bg': '#F9DEDC',
      'selection-text': '#410E0B',
      background: '#FFF8F7',
      surface: '#FFF8F7',
      'on-background': '#201A19',
      'on-surface': '#201A19',
      'surface-variant': '#F5DDDB',
      'on-surface-variant': '#534341',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#FEF1EF',
      'surface-container': '#F9EBE9',
      'surface-container-high': '#F3E5E3',
      'surface-container-highest': '#EEE0DE',
      outline: '#857370',
      'outline-variant': '#D8C2BE',
      'inverse-surface': '#362020',
      'inverse-on-surface': '#F9EBE9',
    },
    dark: {
      primary: '#FFB4AB',
      'primary-container': '#8C1D18',
      'on-primary': '#690005',
      'on-primary-container': '#F9DEDC',
      secondary: '#E7BDB8',
      'secondary-container': '#5D3F3C',
      'on-secondary': '#442926',
      'on-secondary-container': '#FFDAD6',
      tertiary: '#DFC36A',
      'tertiary-container': '#584519',
      'on-tertiary': '#3D2F00',
      'on-tertiary-container': '#FDDEA2',
      'inverse-primary': '#B3261E',
      'selection-bg': '#8C1D18',
      'selection-text': '#F9DEDC',
      background: '#141110',
      surface: '#141110',
      'on-background': '#EDE0DE',
      'on-surface': '#EDE0DE',
      'surface-variant': '#534341',
      'on-surface-variant': '#D8C2BE',
      'surface-container-lowest': '#0F0B0A',
      'surface-container-low': '#201917',
      'surface-container': '#251D1C',
      'surface-container-high': '#302726',
      'surface-container-highest': '#3B3231',
      outline: '#A08C89',
      'outline-variant': '#534341',
      'inverse-surface': '#EDE0DE',
      'inverse-on-surface': '#362020',
    },
  },
  amber: {
    light: {
      primary: '#6D5E00',
      'primary-container': '#FBE14D',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#211B00',
      secondary: '#655E3F',
      'secondary-container': '#EDE4BB',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#201C04',
      tertiary: '#416652',
      'tertiary-container': '#C3ECCE',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#002112',
      'inverse-primary': '#DCC84C',
      'selection-bg': '#FBE14D',
      'selection-text': '#211B00',
      background: '#FFFBF0',
      surface: '#FFFBF0',
      'on-background': '#1E1B10',
      'on-surface': '#1E1B10',
      'surface-variant': '#EAE2CF',
      'on-surface-variant': '#4B4636',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F9F3E3',
      'surface-container': '#F3EDDD',
      'surface-container-high': '#EDE7D7',
      'surface-container-highest': '#E7E2D2',
      outline: '#7C7767',
      'outline-variant': '#CEC6B2',
      'inverse-surface': '#333027',
      'inverse-on-surface': '#F3EDDD',
    },
    dark: {
      primary: '#DCC84C',
      'primary-container': '#524600',
      'on-primary': '#383000',
      'on-primary-container': '#FBE14D',
      secondary: '#D0C8A1',
      'secondary-container': '#4C4728',
      'on-secondary': '#363115',
      'on-secondary-container': '#EDE4BB',
      tertiary: '#A8D0B4',
      'tertiary-container': '#294D38',
      'on-tertiary': '#163325',
      'on-tertiary-container': '#C3ECCE',
      'inverse-primary': '#6D5E00',
      'selection-bg': '#524600',
      'selection-text': '#FBE14D',
      background: '#15130A',
      surface: '#15130A',
      'on-background': '#E7E2D2',
      'on-surface': '#E7E2D2',
      'surface-variant': '#4B4636',
      'on-surface-variant': '#CEC6B2',
      'surface-container-lowest': '#100E06',
      'surface-container-low': '#1E1B10',
      'surface-container': '#221F14',
      'surface-container-high': '#2D2A1E',
      'surface-container-highest': '#383429',
      outline: '#998F77',
      'outline-variant': '#4B4636',
      'inverse-surface': '#E7E2D2',
      'inverse-on-surface': '#333027',
    },
  },
  teal: {
    light: {
      primary: '#006876',
      'primary-container': '#A5EEFF',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#001F25',
      secondary: '#4A6268',
      'secondary-container': '#CCE8EF',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#041E23',
      tertiary: '#525E7D',
      'tertiary-container': '#DAE2FF',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#0C1537',
      'inverse-primary': '#53D5E7',
      'selection-bg': '#A5EEFF',
      'selection-text': '#001F25',
      background: '#F5FAFB',
      surface: '#F5FAFB',
      'on-background': '#171D1E',
      'on-surface': '#171D1E',
      'surface-variant': '#DAE4E7',
      'on-surface-variant': '#3F494B',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#EFF5F6',
      'surface-container': '#E9F3F5',
      'surface-container-high': '#E3EDF0',
      'surface-container-highest': '#DEE8EA',
      outline: '#6F797B',
      'outline-variant': '#BEC9CB',
      'inverse-surface': '#2B3133',
      'inverse-on-surface': '#EFF5F6',
    },
    dark: {
      primary: '#53D5E7',
      'primary-container': '#004E5A',
      'on-primary': '#003640',
      'on-primary-container': '#A5EEFF',
      secondary: '#B0CCCF',
      'secondary-container': '#324B50',
      'on-secondary': '#1B3439',
      'on-secondary-container': '#CCE8EF',
      tertiary: '#BAC6E8',
      'tertiary-container': '#3A4664',
      'on-tertiary': '#232F4D',
      'on-tertiary-container': '#DAE2FF',
      'inverse-primary': '#006876',
      'selection-bg': '#004E5A',
      'selection-text': '#A5EEFF',
      background: '#0F1415',
      surface: '#0F1415',
      'on-background': '#DEE4E5',
      'on-surface': '#DEE4E5',
      'surface-variant': '#3F494B',
      'on-surface-variant': '#BEC9CB',
      'surface-container-lowest': '#0A0F10',
      'surface-container-low': '#171D1E',
      'surface-container': '#1B2021',
      'surface-container-high': '#262B2C',
      'surface-container-highest': '#313637',
      outline: '#899294',
      'outline-variant': '#3F494B',
      'inverse-surface': '#DEE4E5',
      'inverse-on-surface': '#2B3133',
    },
  },
  indigo: {
    light: {
      primary: '#4355B9',
      'primary-container': '#DEE0FF',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#00006E',
      secondary: '#5C5D72',
      'secondary-container': '#E1E0F9',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#18192B',
      tertiary: '#78536B',
      'tertiary-container': '#FFD7F2',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#2E1126',
      'inverse-primary': '#BEC2FF',
      'selection-bg': '#DEE0FF',
      'selection-text': '#00006E',
      background: '#FAFAFE',
      surface: '#FAFAFE',
      'on-background': '#1B1B21',
      'on-surface': '#1B1B21',
      'surface-variant': '#E3E0F0',
      'on-surface-variant': '#46464F',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F4F3FA',
      'surface-container': '#EEEDF4',
      'surface-container-high': '#E8E7EE',
      'surface-container-highest': '#E3E2E9',
      outline: '#777680',
      'outline-variant': '#C8C5D0',
      'inverse-surface': '#303036',
      'inverse-on-surface': '#F3F0F4',
    },
    dark: {
      primary: '#BEC2FF',
      'primary-container': '#2B3EA0',
      'on-primary': '#0F1578',
      'on-primary-container': '#DEE0FF',
      secondary: '#C5C4DD',
      'secondary-container': '#44465A',
      'on-secondary': '#2E2F42',
      'on-secondary-container': '#E1E0F9',
      tertiary: '#EAB8D5',
      'tertiary-container': '#5E3B52',
      'on-tertiary': '#44243C',
      'on-tertiary-container': '#FFD7F2',
      'inverse-primary': '#4355B9',
      'selection-bg': '#2B3EA0',
      'selection-text': '#DEE0FF',
      background: '#131318',
      surface: '#131318',
      'on-background': '#E4E1E6',
      'on-surface': '#E4E1E6',
      'surface-variant': '#46464F',
      'on-surface-variant': '#C7C5D0',
      'surface-container-lowest': '#0E0E13',
      'surface-container-low': '#1B1B21',
      'surface-container': '#1F1F26',
      'surface-container-high': '#2A2930',
      'surface-container-highest': '#35343B',
      outline: '#908F9A',
      'outline-variant': '#46464F',
      'inverse-surface': '#E4E1E6',
      'inverse-on-surface': '#303036',
    },
  },
  purple: {
    light: {
      primary: '#65558F',
      'primary-container': '#EADDFF',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#21005D',
      secondary: '#625B71',
      'secondary-container': '#E8DEF8',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#1D192B',
      tertiary: '#7D5260',
      'tertiary-container': '#FFD8E4',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#31111D',
      'inverse-primary': '#D0BCFF',
      'selection-bg': '#EADDFF',
      'selection-text': '#21005D',
      background: '#FEF7FF',
      surface: '#FEF7FF',
      'on-background': '#1D1B20',
      'on-surface': '#1D1B20',
      'surface-variant': '#E7E0EC',
      'on-surface-variant': '#49454F',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F7F2FA',
      'surface-container': '#F3EDF7',
      'surface-container-high': '#ECE6F0',
      'surface-container-highest': '#E6E0E9',
      outline: '#79747E',
      'outline-variant': '#CAC4D0',
      'inverse-surface': '#322F35',
      'inverse-on-surface': '#F5EFF7',
    },
    dark: {
      primary: '#D0BCFF',
      'primary-container': '#4F378B',
      'on-primary': '#381E72',
      'on-primary-container': '#EADDFF',
      secondary: '#CCC2DC',
      'secondary-container': '#4A4458',
      'on-secondary': '#332D41',
      'on-secondary-container': '#E8DEF8',
      tertiary: '#EFB8C8',
      'tertiary-container': '#633B48',
      'on-tertiary': '#492532',
      'on-tertiary-container': '#FFD8E4',
      'inverse-primary': '#65558F',
      'selection-bg': '#4F378B',
      'selection-text': '#EADDFF',
      background: '#111318',
      surface: '#111318',
      'on-background': '#E6E0E9',
      'on-surface': '#E6E0E9',
      'surface-variant': '#49454F',
      'on-surface-variant': '#CAC4D0',
      'surface-container-lowest': '#0E0D13',
      'surface-container-low': '#1A1720',
      'surface-container': '#1D1B20',
      'surface-container-high': '#2B2930',
      'surface-container-highest': '#36343B',
      outline: '#938F99',
      'outline-variant': '#49454F',
      'inverse-surface': '#E6E0E9',
      'inverse-on-surface': '#322F35',
    },
  },
  blue: {
    light: {
      primary: '#1565C0',
      'primary-container': '#D7E3FF',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#001849',
      secondary: '#565E71',
      'secondary-container': '#DAE2F9',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#121C2B',
      tertiary: '#705574',
      'tertiary-container': '#FAD8FF',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#28002E',
      'inverse-primary': '#ADC6FF',
      'selection-bg': '#D7E3FF',
      'selection-text': '#001849',
      background: '#F8F9FF',
      surface: '#F8F9FF',
      'on-background': '#1A1B21',
      'on-surface': '#1A1B21',
      'surface-variant': '#E1E2EC',
      'on-surface-variant': '#44474E',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F3F3FA',
      'surface-container': '#EDEEF5',
      'surface-container-high': '#E7E8EF',
      'surface-container-highest': '#E2E2E9',
      outline: '#74777F',
      'outline-variant': '#C4C6D0',
      'inverse-surface': '#2F3036',
      'inverse-on-surface': '#F1F0F7',
    },
    dark: {
      primary: '#ADC6FF',
      'primary-container': '#0042A1',
      'on-primary': '#002884',
      'on-primary-container': '#D7E3FF',
      secondary: '#BEC6DC',
      'secondary-container': '#3E4759',
      'on-secondary': '#283141',
      'on-secondary-container': '#DAE2F9',
      tertiary: '#E5BAE8',
      'tertiary-container': '#573B5B',
      'on-tertiary': '#3F1C44',
      'on-tertiary-container': '#FAD8FF',
      'inverse-primary': '#1565C0',
      'selection-bg': '#0042A1',
      'selection-text': '#D7E3FF',
      background: '#111319',
      surface: '#111319',
      'on-background': '#E2E2E9',
      'on-surface': '#E2E2E9',
      'surface-variant': '#44474E',
      'on-surface-variant': '#C4C6D0',
      'surface-container-lowest': '#0D0E13',
      'surface-container-low': '#191B20',
      'surface-container': '#1D1F24',
      'surface-container-high': '#282A2F',
      'surface-container-highest': '#33353A',
      outline: '#8E9099',
      'outline-variant': '#44474E',
      'inverse-surface': '#E2E2E9',
      'inverse-on-surface': '#2F3036',
    },
  },
  green: {
    light: {
      primary: '#006E1C',
      'primary-container': '#96F990',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#002204',
      secondary: '#52634E',
      'secondary-container': '#D4EECB',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#0F1F0C',
      tertiary: '#38626D',
      'tertiary-container': '#BCEBF7',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#001F26',
      'inverse-primary': '#7BDB7C',
      'selection-bg': '#96F990',
      'selection-text': '#002204',
      background: '#F6FBF3',
      surface: '#F6FBF3',
      'on-background': '#191C18',
      'on-surface': '#191C18',
      'surface-variant': '#DDE5DA',
      'on-surface-variant': '#424940',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F0F5ED',
      'surface-container': '#EAF0E7',
      'surface-container-high': '#E4EAE1',
      'surface-container-highest': '#DEE4DB',
      outline: '#72796F',
      'outline-variant': '#C1C9BD',
      'inverse-surface': '#2D312C',
      'inverse-on-surface': '#F0F5ED',
    },
    dark: {
      primary: '#7BDB7C',
      'primary-container': '#005316',
      'on-primary': '#003909',
      'on-primary-container': '#96F990',
      secondary: '#B9D1B3',
      'secondary-container': '#3B4B38',
      'on-secondary': '#253523',
      'on-secondary-container': '#D4EECB',
      tertiary: '#A1CFD9',
      'tertiary-container': '#1E4A55',
      'on-tertiary': '#00363D',
      'on-tertiary-container': '#BCEBF7',
      'inverse-primary': '#006E1C',
      'selection-bg': '#005316',
      'selection-text': '#96F990',
      background: '#11130F',
      surface: '#11130F',
      'on-background': '#E1E3DE',
      'on-surface': '#E1E3DE',
      'surface-variant': '#424940',
      'on-surface-variant': '#C1C9BD',
      'surface-container-lowest': '#0C0F0B',
      'surface-container-low': '#191C18',
      'surface-container': '#1D201C',
      'surface-container-high': '#272B26',
      'surface-container-highest': '#323531',
      outline: '#8C9389',
      'outline-variant': '#424940',
      'inverse-surface': '#E1E3DE',
      'inverse-on-surface': '#2E312D',
    },
  },
  rose: {
    light: {
      primary: '#9E163B',
      'primary-container': '#FFD9E2',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#400016',
      secondary: '#74565F',
      'secondary-container': '#FFD9E3',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#2B1520',
      tertiary: '#7A5731',
      'tertiary-container': '#FFDDB8',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#2C1600',
      'inverse-primary': '#FFB1C2',
      'selection-bg': '#FFD9E2',
      'selection-text': '#400016',
      background: '#FFF8F7',
      surface: '#FFF8F7',
      'on-background': '#201A1B',
      'on-surface': '#201A1B',
      'surface-variant': '#EDDDE1',
      'on-surface-variant': '#4D3F42',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#FFF0F2',
      'surface-container': '#FAEAEC',
      'surface-container-high': '#F4E4E6',
      'surface-container-highest': '#EEE0E2',
      outline: '#85737A',
      'outline-variant': '#D5C2C6',
      'inverse-surface': '#362D2E',
      'inverse-on-surface': '#FAEAEC',
    },
    dark: {
      primary: '#FFB1C2',
      'primary-container': '#7D0026',
      'on-primary': '#650022',
      'on-primary-container': '#FFD9E2',
      secondary: '#E3BDCA',
      'secondary-container': '#5B3F48',
      'on-secondary': '#43292E',
      'on-secondary-container': '#FFD9E3',
      tertiary: '#EEBF90',
      'tertiary-container': '#61411A',
      'on-tertiary': '#462900',
      'on-tertiary-container': '#FFDDB8',
      'inverse-primary': '#9E163B',
      'selection-bg': '#7D0026',
      'selection-text': '#FFD9E2',
      background: '#14100F',
      surface: '#14100F',
      'on-background': '#EDE0E1',
      'on-surface': '#EDE0E1',
      'surface-variant': '#4D3F42',
      'on-surface-variant': '#D5C2C6',
      'surface-container-lowest': '#0F0B0B',
      'surface-container-low': '#201A1B',
      'surface-container': '#261E20',
      'surface-container-high': '#302829',
      'surface-container-highest': '#3C3234',
      outline: '#9E8C8F',
      'outline-variant': '#4D3F42',
      'inverse-surface': '#EDE0E1',
      'inverse-on-surface': '#362D2E',
    },
  },
  orange: {
    light: {
      primary: '#9A4200',
      'primary-container': '#FFDBCA',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#340F00',
      secondary: '#7E5740',
      'secondary-container': '#FFDBC9',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#30180A',
      tertiary: '#686032',
      'tertiary-container': '#F1E4AA',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#1F1800',
      'inverse-primary': '#FFB590',
      'selection-bg': '#FFDBCA',
      'selection-text': '#340F00',
      background: '#FFF8F5',
      surface: '#FFF8F5',
      'on-background': '#211712',
      'on-surface': '#211712',
      'surface-variant': '#F4DED4',
      'on-surface-variant': '#514239',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#FFF1EB',
      'surface-container': '#FAEBE5',
      'surface-container-high': '#F4E5DF',
      'surface-container-highest': '#EEE0DA',
      outline: '#85736A',
      'outline-variant': '#D8C2B8',
      'inverse-surface': '#382E2A',
      'inverse-on-surface': '#FAEBE5',
    },
    dark: {
      primary: '#FFB590',
      'primary-container': '#762F00',
      'on-primary': '#511900',
      'on-primary-container': '#FFDBCA',
      secondary: '#EDBBAA',
      'secondary-container': '#63402B',
      'on-secondary': '#4A2416',
      'on-secondary-container': '#FFDBC9',
      tertiary: '#D4C882',
      'tertiary-container': '#504B1C',
      'on-tertiary': '#34300C',
      'on-tertiary-container': '#F1E4AA',
      'inverse-primary': '#9A4200',
      'selection-bg': '#762F00',
      'selection-text': '#FFDBCA',
      background: '#13100D',
      surface: '#13100D',
      'on-background': '#ECE0D8',
      'on-surface': '#ECE0D8',
      'surface-variant': '#514239',
      'on-surface-variant': '#D8C2B8',
      'surface-container-lowest': '#0E0B09',
      'surface-container-low': '#1E1915',
      'surface-container': '#221D19',
      'surface-container-high': '#2D2720',
      'surface-container-highest': '#38312C',
      outline: '#A08D83',
      'outline-variant': '#514239',
      'inverse-surface': '#ECE0D8',
      'inverse-on-surface': '#382E2A',
    },
  },
}

function isThemePreference(value: string | null): value is ThemePreference {
  return value === 'system' || value === 'light' || value === 'dark'
}

const ACCENT_COLORS = new Set<string>(['red', 'rose', 'orange', 'amber', 'green', 'teal', 'blue', 'indigo', 'purple'])

function isAccentColor(value: string | null): value is AccentColor {
  return value != null && ACCENT_COLORS.has(value)
}

function getSystemTheme(): 'light' | 'dark' {
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}

function applyAccentColors(theme: ThemeController, accent: AccentColor): void {
  const palette = ACCENT_PALETTES[accent]
  Object.assign(theme.themes.value.light.colors, palette.light)
  Object.assign(theme.themes.value.dark.colors, palette.dark)
}

function applyTheme(theme: ThemeController, preference: ThemePreference): void {
  const themeName = preference === 'system' ? getSystemTheme() : preference
  applyAccentColors(theme, getAccentPreference())
  theme.change(themeName)
}

export function getThemePreference(): ThemePreference {
  const storedValue = window.localStorage.getItem(THEME_PREFERENCE_KEY)
  return isThemePreference(storedValue) ? storedValue : 'dark'
}

export function setThemePreference(theme: ThemeController, preference: ThemePreference): void {
  window.localStorage.setItem(THEME_PREFERENCE_KEY, preference)
  applyTheme(theme, preference)
}

export function getAccentPreference(): AccentColor {
  const storedValue = window.localStorage.getItem(ACCENT_PREFERENCE_KEY)
  return isAccentColor(storedValue) ? storedValue : 'purple'
}

export function setAccentPreference(theme: ThemeController, accent: AccentColor): void {
  window.localStorage.setItem(ACCENT_PREFERENCE_KEY, accent)
  applyAccentColors(theme, accent)
}

export function initializeTheme(theme: ThemeController): void {
  applyTheme(theme, getThemePreference())

  const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
  const handleSystemThemeChange = () => {
    if (getThemePreference() === 'system') {
      applyTheme(theme, 'system')
    }
  }

  if (typeof mediaQuery.addEventListener === 'function') {
    mediaQuery.addEventListener('change', handleSystemThemeChange)
    return
  }

  mediaQuery.addListener(handleSystemThemeChange)
}
