import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'

export const vuetify = createVuetify({
  theme: {
    defaultTheme: 'dark',
    variations: {
      colors: ['primary', 'secondary', 'tertiary', 'info', 'success', 'warning'],
      lighten: 2,
      darken: 2,
    },
    themes: {
      light: {
        colors: {
          primary: '#65558F',
          'primary-container': '#EADDFF',
          'on-primary': '#FFFFFF',
          'on-primary-container': '#21005D',
          secondary: '#625B71',
          'secondary-container': '#E8DEF8',
          'on-secondary': '#FFFFFF',
          'on-secondary-container': '#1D192B',
          tertiary: '#7D5260',
          'tertiary-container': '#FFD8E4',
          'on-tertiary': '#FFFFFF',
          'on-tertiary-container': '#31111D',
          error: '#B3261E',
          'error-container': '#F9DEDC',
          'on-error': '#FFFFFF',
          'on-error-container': '#410E0B',
          background: '#FEF7FF',
          'on-background': '#1D1B20',
          surface: '#FEF7FF',
          'surface-variant': '#E7E0EC',
          'surface-container-lowest': '#FFFFFF',
          'surface-container-low': '#F7F2FA',
          'surface-container': '#F3EDF7',
          'surface-container-high': '#ECE6F0',
          'surface-container-highest': '#E6E0E9',
          'on-surface': '#1D1B20',
          'on-surface-variant': '#49454F',
          outline: '#79747E',
          'outline-variant': '#CAC4D0',
          'inverse-surface': '#322F35',
          'inverse-on-surface': '#F5EFF7',
          'inverse-primary': '#D0BCFF',
          scrim: '#000000',
          'selection-bg': '#EADDFF',
          'selection-text': '#21005D',
          info: '#7A9AC9',
          'on-info': '#152238',
          success: '#6B9478',
          'on-success': '#121C16',
          warning: '#C49A6A',
          'on-warning': '#261C12',
        },
      },
      dark: {
        colors: {
          primary: '#D0BCFF',
          'primary-container': '#4F378B',
          'on-primary': '#381E72',
          'on-primary-container': '#EADDFF',
          secondary: '#CCC2DC',
          'secondary-container': '#4A4458',
          'on-secondary': '#332D41',
          'on-secondary-container': '#E8DEF8',
          tertiary: '#EFB8C8',
          'tertiary-container': '#633B48',
          'on-tertiary': '#492532',
          'on-tertiary-container': '#FFD8E4',
          error: '#F2B8B5',
          'error-container': '#8C1D18',
          'on-error': '#690005',
          'on-error-container': '#F9DEDC',
          background: '#111318',
          'on-background': '#E6E0E9',
          surface: '#111318',
          'surface-variant': '#49454F',
          'surface-container-lowest': '#0E0D13',
          'surface-container-low': '#1A1720',
          'surface-container': '#1D1B20',
          'surface-container-high': '#2B2930',
          'surface-container-highest': '#36343B',
          'on-surface': '#E6E0E9',
          'on-surface-variant': '#CAC4D0',
          outline: '#938F99',
          'outline-variant': '#49454F',
          'inverse-surface': '#E6E0E9',
          'inverse-on-surface': '#322F35',
          'inverse-primary': '#65558F',
          scrim: '#000000',
          'selection-bg': '#4F378B',
          'selection-text': '#EADDFF',
          info: '#9BB9E8',
          'on-info': '#0D1524',
          success: '#A3D4B0',
          'on-success': '#0C1810',
          warning: '#E4C995',
          'on-warning': '#1C1608',
        },
      },
    },
  },
  defaults: {
    VBtn: {
      rounded: 'xl',
    },
    VBtnToggle: {
      rounded: 'xl',
      divided: true,
    },
    VTextField: {
      variant: 'outlined',
    },
    VCard: {
      rounded: 'lg',
    },
    VList: {
      bgColor: 'transparent',
    },
    VListItem: {
      rounded: 'lg',
    },
    VToolbar: {
      density: 'comfortable',
    },
    VNavigationDrawer: {
      color: 'surface-container',
    },
  },
})
